name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        nim: [ 'stable' ]
        os: [ 'ubuntu-20.04' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim }}
      - run: nim --version && nimble -y -d:release build
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ttop"
          makeLatest: true
