name: Build

on:
  push:
    tags:
    - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - run: sudo apt-get -y install musl-tools
      - uses: actions/checkout@v3
      - uses: jiro4989/setup-nim-action@v1
      - run: nim --version && nimble -y install -d && nimble static && nimble staticdebug
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "ttop,ttop-debug"
          makeLatest: true
          allowUpdates: true

  aur:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v2
      - uses: ulises-jeremias/github-actions-aur-publish@v1
        with:
          pkgname: ttop
          pkgbuild: aur/PKGBUILD
          assets: aur/.INSTALL
          commit_username: ${{ secrets.AUR_USERNAME }}
          commit_email: ${{ secrets.AUR_EMAIL }}
          ssh_private_key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
          commit_message: Update AUR package
          update_pkgver: true
